default:
  tags:
    - nix

include:
  - local: .gitlab-ci/build.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push"
  - local: .gitlab-ci/update.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"

    
