name: Attic

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Set up nix
        run: |
          mkdir -p $HOME/.config/nix
          cat <<CONFIG > $HOME/.config/nix/nix.conf
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN_GITHUB }}
          cores = 2
          max-jobs = 2
          CONFIG
      - name: Set up attic
        run: attic login --set-default chvp https://attic.chvp.be "${{ secrets.ATTIC_AUTH_TOKEN }}"
      - name: Build and cache all
        run: bash build_and_cache_all.sh
