name: Update

on:
  schedule:
    - cron: '45 */2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Set up extra git auth
        run: |
          git config --local "includeIf.gitdir:$(pwd)/.git.path" "$(git config --local includeIf.gitdir:$(pwd | sed 's#private/##')/.git.path)"
      - name: Set up nix
        run: |
          mkdir -p $HOME/.config/nix
          cat <<CONFIG > $HOME/.config/nix/nix.conf
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN_GITHUB }}
          cores = 2
          max-jobs = 2
          CONFIG
      - name: Set up attic
        run: attic login --set-default chvp https://attic.chvp.be "${{ secrets.ATTIC_AUTH_TOKEN }}"
      - run: nix flake update
      - name: Build and cache all
        run: bash build_and_cache_all.sh
      - name: Commit and push
        if: ${{ success() }}
        run: |
          if [ "$(git status --porcelain=v1 | wc -l)" != "0" ]
          then
            git status --porcelain=v1
            git add .
            git -c "user.name=CharBOTte" -c "user.email=commit-bot@chvp.be" commit -m "Update dependencies"
            git push origin
          else
            echo "Nothing to commit"
          fi
