name: Update

on:
  schedule:
    - cron: '45 */2 * * *'
  workflow_dispatch:

env:
  USER: root

jobs:
  update:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up extra git auth
        run: |
          git config --local "includeIf.gitdir:$(pwd)/.git.path" "$(git config --local includeIf.gitdir:$(pwd | sed 's#private/##')/.git.path)"
      - name: Set up nix
        run: |
          mkdir -p $HOME/.config/nix
          echo "access-tokens = github.com=${{ secrets.ACCESS_TOKEN_GITHUB }}" > $HOME/.config/nix/nix.conf
      - name: Set up attic
        run: attic login --set-default chvp https://attic.chvp.be "${{ secrets.ATTIC_AUTH_TOKEN }}"
      - run: nix flake update
        id: update
      - name: Build and cache elendel
        run: |
          nix build -L --no-link .#nixosConfigurations.elendel.config.system.build.toplevel
          nix eval --json ".#nixosConfigurations.elendel.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | attic push chvp --stdin
        if: ${{ steps.update.conclusion == 'success' }}
      - name: Build and cache kharbranth
        run: |
          nix build -L --no-link .#nixosConfigurations.kharbranth.config.system.build.toplevel
          nix eval --json ".#nixosConfigurations.kharbranth.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | attic push chvp --stdin
        if: ${{ steps.update.conclusion == 'success' }}
      - name: Build and cache kholinar
        run: |
          nix build -L --no-link .#nixosConfigurations.kholinar.config.system.build.toplevel
          nix eval --json ".#nixosConfigurations.kholinar.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | attic push chvp --stdin
        if: ${{ steps.update.conclusion == 'success' }}
      - name: Build and cache marabethia
        run: |
          nix build -L --no-link .#nixosConfigurations.marabethia.config.system.build.toplevel
          nix eval --json ".#nixosConfigurations.marabethia.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | attic push chvp --stdin
        if: ${{ steps.update.conclusion == 'success' }}
      - name: Build and cache purelake
        run: |
          nix build -L --no-link .#nixosConfigurations.purelake.config.system.build.toplevel
          nix eval --json ".#nixosConfigurations.purelake.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | attic push chvp --stdin
        if: ${{ steps.update.conclusion == 'success' }}
      - name: Commit and push
        if: ${{ success() }}
        run: |
          if [ "$(git status --porcelain=v1 | wc -l)" != "0" ]
          then
            git status --porcelain=v1
            git add .
            git -c "user.name=CharBOTte" -c "user.email=commit-bot@chvp.be" commit -m "Update dependencies"
            git push origin
          else
            echo "Nothing to commit"
          fi
