mu4e-compose-mode

(mvg
 "Met vriendelijke groeten" n
 "Charlotte Van Petegem"
 )

(kindr
 "Kind regards" n
 "Charlotte Van Petegem"
 )

(domvg
 "Met vriendelijke groeten" n
 "Charlotte Van Petegem" n
 "Developer" n n
 "Dodona Learning Technologies BV" n
 "Ottergemsesteenweg-Zuid 808, box B226" n
 "B-9000 Ghent"
 )

(dokr
 "Kind regards" n
 "Charlotte Van Petegem" n
 "Developer" n n
 "Dodona Learning Technologies BV" n
 "Ottergemsesteenweg-Zuid 808, box B226" n
 "B-9000 Ghent"
 )
