name: Update

on:
  schedule:
    - cron: '30 */2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: chvp
          extraPullNames: "nix-community,accentor"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix flake update
      - run: nix build -L --no-link .#nixosConfigurations.lasting-integrity.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.lasting-integrity.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push chvp
      - run: nix build -L --no-link .#nixosConfigurations.urithiru.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.urithiru.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push chvp
      - run: nix build -L --no-link .#nixosConfigurations.kharbranth.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.kharbranth.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push chvp
      - run: nix build -L --no-link .#nixosConfigurations.kholinar.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.kholinar.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push chvp
      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: "Update dependencies"
